import os
import shutil

home_dir = os.path.expanduser("~")
base_templates_dir = f"{home_dir}/.bricks"

# Configuration for defaults from local environment
DEFAULT_BASE_URL = "https://newsapi.org/"
DEFAULT_API_KEY = ""

# Try to read values from current local.properties to use as defaults in Mason
if os.path.exists("local.properties"):
    with open("local.properties", "r") as f:
        for line in f:
            if line.startswith("API_KEY="):
                val = line.split("=")[1].strip()
                if val: DEFAULT_API_KEY = val
            if line.startswith("BASE_URL="):
                val = line.split("=")[1].strip()
                if val: DEFAULT_BASE_URL = val

if os.path.exists(f"{base_templates_dir}/android_core_setup"):
    shutil.rmtree(f"{base_templates_dir}/android_core_setup")
if os.path.exists(f"{base_templates_dir}/android_feature"):
    shutil.rmtree(f"{base_templates_dir}/android_feature")

os.makedirs(base_templates_dir, exist_ok=True)

def create_dir(path):
    os.makedirs(path, exist_ok=True)

# ---------------------------------------------------------
# BRICK 1: android_core_setup (TOTALLY STANDALONE)
# ---------------------------------------------------------
core_brick = "android_core_setup"
core_dir = f"{base_templates_dir}/{core_brick}/__brick__"
core_src_dir = f"{core_dir}/app/src/main/java/{{{{package_name.pathCase()}}}}"

create_dir(core_src_dir)

# 1.1 brick.yaml for core
with open(f"{base_templates_dir}/{core_brick}/brick.yaml", "w") as f:
    f.write(f"""name: android_core_setup
description: Clean Architecture Android Core Setup (Standalone Open Source)
version: 0.1.0+1
environment:
  mason: ">=0.1.0-dev <0.2.0"
vars:
  package_name:
    type: string
    description: "The package name (e.g., com.example.app)"
    default: "com.example.app"
  app_name:
    type: string
    description: "The application class name (e.g., App)"
    default: "App"
  base_url:
    type: string
    description: "The API Base URL"
    default: "{DEFAULT_BASE_URL}"
  api_key:
    type: string
    description: "The API Key"
    default: "{DEFAULT_API_KEY}"
""")

# 1.1.1 Create local.properties in the brick
with open(f"{core_dir}/local.properties", "w") as f:
    f.write("""# Automatically generated by Mason
BASE_URL={{base_url}}
API_KEY={{api_key}}
""")

# 1.2 core/Constants.kt
create_dir(f"{core_src_dir}/core")
with open(f"{core_src_dir}/core/Constants.kt", "w") as f:
    f.write("""package {{package_name}}.core

object Constants {
    const val BASE_URL = "{{base_url}}"
    const val DATABASE_NAME = "app_database"
}
""")

# 1.3 core/Extensions.kt
with open(f"{core_src_dir}/core/Extensions.kt", "w") as f:
    f.write("""package {{package_name}}.core

import android.view.View
import android.widget.Toast
import androidx.fragment.app.Fragment

fun View.show() { visibility = View.VISIBLE }
fun View.hide() { visibility = View.GONE }

fun Fragment.toast(message: String) {
    Toast.makeText(requireContext(), message, Toast.LENGTH_SHORT).show()
}
""")

# 1.3.1 core/utils/NetworkMonitor.kt
create_dir(f"{core_src_dir}/core/utils")
with open(f"{core_src_dir}/core/utils/NetworkMonitor.kt", "w") as f:
    f.write("""package {{package_name}}.core.utils

import android.content.Context
import android.net.ConnectivityManager
import android.net.Network
import android.net.NetworkCapabilities
import android.net.NetworkRequest
import dagger.hilt.android.qualifiers.ApplicationContext
import kotlinx.coroutines.channels.awaitClose
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.callbackFlow
import kotlinx.coroutines.flow.distinctUntilChanged
import kotlinx.coroutines.flow.first
import javax.inject.Inject
import javax.inject.Singleton

interface NetworkMonitor {
    val isOnline: Flow<Boolean>
    suspend fun isCurrentlyOnline(): Boolean
}

@Singleton
class ConnectivityObserver @Inject constructor(@param:ApplicationContext private val context: Context) :
    NetworkMonitor {
    private val connectivityManager =
        context.getSystemService(Context.CONNECTIVITY_SERVICE) as ConnectivityManager

    override val isOnline: Flow<Boolean> = callbackFlow {
        val callback = object : ConnectivityManager.NetworkCallback() {
            override fun onAvailable(network: Network) {
                channel.trySend(true)
            }

            override fun onLost(network: Network) {
                channel.trySend(false)
            }

            override fun onCapabilitiesChanged(
                network: Network,
                networkCapabilities: NetworkCapabilities
            ) {
                val hasInternet =
                    networkCapabilities.hasCapability(NetworkCapabilities.NET_CAPABILITY_INTERNET)
                channel.trySend(hasInternet)
            }
        }
        val request = NetworkRequest.Builder()
            .addCapability(NetworkCapabilities.NET_CAPABILITY_INTERNET)
            .build()

        connectivityManager.registerNetworkCallback(request, callback)

        val initialStatus = connectivityManager.activeNetwork?.let { network ->
            connectivityManager.getNetworkCapabilities(network)?.hasCapability(NetworkCapabilities.NET_CAPABILITY_INTERNET)
        } ?: false
        channel.trySend(initialStatus)
        awaitClose {
            connectivityManager.unregisterNetworkCallback(callback)
        }

    }.distinctUntilChanged()

    override suspend fun isCurrentlyOnline(): Boolean {
        return isOnline.first()
    }
}
""")

# 1.4 core/di/NetworkModule.kt
create_dir(f"{core_src_dir}/core/di")
with open(f"{core_src_dir}/core/di/NetworkModule.kt", "w") as f:
    f.write("""package {{package_name}}.core.di

import {{package_name}}.core.Constants
import {{package_name}}.data.source.remote.ApiService
import dagger.Module
import dagger.Provides
import dagger.hilt.InstallIn
import dagger.hilt.components.SingletonComponent
import okhttp3.OkHttpClient
import okhttp3.logging.HttpLoggingInterceptor
import retrofit2.Retrofit
import retrofit2.converter.gson.GsonConverterFactory
import javax.inject.Singleton

@Module
@InstallIn(SingletonComponent::class)
object NetworkModule {

    @Provides
    @Singleton
    fun provideLoggingInterceptor(): HttpLoggingInterceptor {
        return HttpLoggingInterceptor().apply {
            level = HttpLoggingInterceptor.Level.BODY
        }
    }

    @Provides
    @Singleton
    fun provideOkHttpClient(loggingInterceptor: HttpLoggingInterceptor): OkHttpClient {
        return OkHttpClient.Builder()
            .addInterceptor(loggingInterceptor)
            .build()
    }

    @Provides
    @Singleton
    fun provideRetrofit(okHttpClient: OkHttpClient): Retrofit {
        return Retrofit.Builder()
            .baseUrl(Constants.BASE_URL)
            .addConverterFactory(GsonConverterFactory.create())
            .client(okHttpClient)
            .build()
    }

    @Provides
    @Singleton
    fun provideApiService(retrofit: Retrofit): ApiService {
        return retrofit.create(ApiService::class.java)
    }
}
""")

# 1.5 core/di/LocalModule.kt
with open(f"{core_src_dir}/core/di/LocalModule.kt", "w") as f:
    f.write("""package {{package_name}}.core.di

import android.content.Context
import androidx.room.Room
import {{package_name}}.core.Constants
import {{package_name}}.data.source.local.room.database.AppDatabase
import {{package_name}}.data.source.local.room.dao.AppDao
import dagger.Module
import dagger.Provides
import dagger.hilt.InstallIn
import dagger.hilt.android.qualifiers.ApplicationContext
import dagger.hilt.components.SingletonComponent
import javax.inject.Singleton

@Module
@InstallIn(SingletonComponent::class)
object LocalModule {

    @Provides
    @Singleton
    fun provideDatabase(@ApplicationContext context: Context): AppDatabase {
        return Room.databaseBuilder(
            context,
            AppDatabase::class.java,
            Constants.DATABASE_NAME
        ).fallbackToDestructiveMigration().build()
    }

    @Provides
    fun provideAppDao(database: AppDatabase): AppDao {
        return database.appDao()
    }
}
""")

# 1.6 core/di/RepositoryModule.kt
with open(f"{core_src_dir}/core/di/RepositoryModule.kt", "w") as f:
    f.write("""package {{package_name}}.core.di

import dagger.Module
import dagger.hilt.InstallIn
import dagger.hilt.components.SingletonComponent

@Module
@InstallIn(SingletonComponent::class)
abstract class RepositoryModule {
    // Bind your repositories here using @Binds
}
""")

# 1.7 data/source/remote/ApiService.kt
create_dir(f"{core_src_dir}/data/source/remote")
with open(f"{core_src_dir}/data/source/remote/ApiService.kt", "w") as f:
    f.write("""package {{package_name}}.data.source.remote

import retrofit2.http.GET

interface ApiService {
    @GET("sample")
    suspend fun getSampleData(): Any
}
""")

# 1.8 data/source/local/room/...
create_dir(f"{core_src_dir}/data/source/local/room/dao")
create_dir(f"{core_src_dir}/data/source/local/room/database")
create_dir(f"{core_src_dir}/data/source/local/room/entity")

with open(f"{core_src_dir}/data/source/local/room/database/AppDatabase.kt", "w") as f:
    f.write("""package {{package_name}}.data.source.local.room.database

import androidx.room.Database
import androidx.room.RoomDatabase
import {{package_name}}.data.source.local.room.dao.AppDao

@Database(entities = [], version = 1, exportSchema = false)
abstract class AppDatabase : RoomDatabase() {
    abstract fun appDao(): AppDao
}
""")

with open(f"{core_src_dir}/data/source/local/room/dao/AppDao.kt", "w") as f:
    f.write("""package {{package_name}}.data.source.local.room.dao

import androidx.room.Dao

@Dao
interface AppDao {
    // Add your DAO methods here
}
""")

# 1.8.1 data/repository/ResponseHelper.kt
create_dir(f"{core_src_dir}/data/repository")
with open(f"{core_src_dir}/data/repository/ResponseHelper.kt", "w") as f:
    f.write("""package {{package_name}}.data.repository

import com.google.gson.Gson
import com.google.gson.JsonObject
import {{package_name}}.domain.model.Resource
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.flow
import retrofit2.Response

open class ResponseHelper {
    private val gson = Gson()

    protected fun <T> saveApiCall(apiCall: suspend () -> Response<T>) : Flow<Resource<T>> = flow {
        emit(Resource.Loading())
        try {
            val response = apiCall()
            if(response.isSuccessful){
                response.body()?.let {
                    emit(Resource.Success(it))
                }    ?: emit(Resource.Error("Empty response body"))

            } else {
                //Read error body once to avoid stream
                val errorBodyString = response.errorBody()?.string()
                val errorMessage = parseErrorMessage(errorBodyString, response.code())
                emit(Resource.Error(errorMessage))

            }
        } catch (e: Exception){
            emit(Resource.Error(e.localizedMessage ?: "An unexpected error occurred"))
        }
    }

    protected fun parseErrorMessage(errorJsonString: String?, responseCode: Int) : String {
        if(errorJsonString.isNullOrBlank()) return "Error :$responseCode"
        return try {
            val jsonObject = gson.fromJson(errorJsonString, JsonObject::class.java)
            if(jsonObject.has("error")){
                jsonObject.get("error").asString
            } else {
                errorJsonString
            }
        } catch (e: Exception){
            errorJsonString
        }
    }
}
""")

# 1.9 domain/model/Resource.kt
create_dir(f"{core_src_dir}/domain/model")
with open(f"{core_src_dir}/domain/model/Resource.kt", "w") as f:
    f.write("""package {{package_name}}.domain.model

sealed class Resource<T>(val data: T? = null, val message: String? = null) {
    class Success<T>(data: T) : Resource<T>(data)
    class Loading<T>(data: T? = null) : Resource<T>(data)
    class Error<T>(message: String, data: T? = null) : Resource<T>(data, message)
}
""")

# 1.10 Create Application class
with open(f"{core_src_dir}/{{{{app_name.pascalCase()}}}}.kt", "w") as f:
    f.write("""package {{package_name}}

import android.app.Application
import dagger.hilt.android.HiltAndroidApp

@HiltAndroidApp
class {{app_name.pascalCase()}} : Application() {
    override fun onCreate() {
        super.onCreate()
    }
}
""")

# 1.11 Standalone Gradle Files
# Root build.gradle.kts
with open(f"{core_dir}/build.gradle.kts", "w") as f:
    f.write("""// Top-level build file where you can add configuration options common to all sub-projects/modules.
plugins {
    alias(libs.plugins.android.application) apply false
    alias(libs.plugins.hilt.android) apply false
    alias(libs.plugins.ksp) apply false
    alias(libs.plugins.kotlin.parcelize) apply false
}
""")

# app/build.gradle.kts
with open(f"{core_dir}/app/build.gradle.kts", "w") as f:
    f.write("""import java.util.Properties
import java.io.FileInputStream

plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.hilt.android)
    alias(libs.plugins.ksp)
    alias(libs.plugins.kotlin.parcelize)
    id("kotlin-parcelize")
}

android {
    namespace = "{{package_name}}"
    compileSdk = 36

    defaultConfig {
        applicationId = "{{package_name}}"
        minSdk = 24
        targetSdk = 36
        versionCode = 1
        versionName = "1.0"

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"

        // Load local.properties for API keys
        val properties = Properties()
        val localPropertiesFile = rootProject.file("local.properties")
        if (localPropertiesFile.exists()) {
            properties.load(FileInputStream(localPropertiesFile))
        }

        val apiKey = properties.getProperty("API_KEY") ?: "{{api_key}}"
        val baseUrl = properties.getProperty("BASE_URL") ?: "{{base_url}}"

        buildConfigField("String", "API_KEY", "\\"$apiKey\\"")
        buildConfigField("String", "BASE_URL", "\\"$baseUrl\\"")
    }

    buildTypes {
        release {
            isMinifyEnabled = false
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }
    buildFeatures {
        buildConfig = true
        viewBinding = true
    }
}

dependencies {
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.appcompat)
    implementation(libs.material)
    implementation(libs.androidx.activity)
    implementation(libs.androidx.constraintlayout)
    implementation(libs.androidx.annotation)
    implementation(libs.androidx.lifecycle.livedata.ktx)
    implementation(libs.androidx.lifecycle.viewmodel.ktx)
    implementation(libs.androidx.fragment.ktx)
    implementation(libs.androidx.swiperefreshlayout)

    // Unit Testing
    testImplementation(libs.junit)
    testImplementation(libs.kotlinx.coroutines.test)
    testImplementation(libs.mockito.core)
    testImplementation(libs.mockito.kotlin)
    testImplementation(libs.androidx.arch.core.testing)

    // DI with Hilt
    implementation(libs.hilt.android)
    ksp(libs.hilt.compiler)

    // Networking
    implementation(libs.gson)
    implementation(libs.retrofit)
    implementation(libs.converter.gson)
    implementation(libs.logging.interceptor)

    // UI
    implementation(libs.glide)
    ksp(libs.glide.compiler)
    implementation(libs.splashscreen)

    // Room
    implementation(libs.androidx.room.runtime)
    ksp(libs.androidx.room.compiler)
    implementation(libs.androidx.room.ktx)
}
""")

# gradle/libs.versions.toml
create_dir(f"{core_dir}/gradle")
with open(f"{core_dir}/gradle/libs.versions.toml", "w") as f:
    f.write("""[versions]
agp = "9.1.0"
kotlin = "2.3.20"
ksp = "2.3.6"
coreKtx = "1.18.0"
appcompat = "1.7.1"
material = "1.13.0"
activity = "1.13.0"
constraintlayout = "2.2.1"
fragment = "1.8.9"
annotation = "1.9.1"
splashscreen = "1.2.0"
glide = "5.0.5"
swiperefreshlayout = "1.1.0"
lifecycle = "2.10.0"
hilt = "2.59.2"
retrofit = "3.0.0"
convertGson = "3.0.0"
loggingInterceptor = "5.3.2"
gson = "2.13.2"
room = "2.8.4"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
coroutinesTest = "1.10.2"
mockito = "5.23.0"
mockitoKotlin = "6.3.0"
archCoreTest = "2.2.0"
browser = "1.10.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-annotation = { group = "androidx.annotation", name = "annotation", version.ref = "annotation" }
splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "splashscreen" }
androidx-fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragment" }
androidx-swiperefreshlayout = { group = "androidx.swiperefreshlayout", name = "swiperefreshlayout", version.ref = "swiperefreshlayout" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "convertGson" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
glide-compiler = { group = "com.github.bumptech.glide", name = "compiler", version.ref = "glide" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutinesTest" }
mockito-core = { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }
mockito-kotlin = { group = "org.mockito.kotlin", name = "mockito-kotlin", version.ref = "mockitoKotlin" }
androidx-arch-core-testing = { group = "androidx.arch.core", name = "core-testing", version.ref = "archCoreTest" }
androidx-browser = { group = "androidx.browser", name="browser", version.ref = "browser"}

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin"}
""")

# ---------------------------------------------------------
# BRICK 2: android_feature
# ---------------------------------------------------------
feature_brick = "android_feature"
feature_dir = f"{base_templates_dir}/{feature_brick}/__brick__"
feature_src_dir = f"{feature_dir}/app/src/main/java/{{{{package_name.pathCase()}}}}"

create_dir(feature_src_dir)

with open(f"{base_templates_dir}/{feature_brick}/brick.yaml", "w") as f:
    f.write("""name: android_feature
description: Generate feature layers (Presenter, Repository, Domain)
version: 0.1.0+1
environment:
  mason: ">=0.1.0-dev <0.2.0"
vars:
  package_name:
    type: string
    description: "The package name (e.g., com.example.app)"
    default: "com.example.app"
  feature_name:
    type: string
    description: "The name of the feature to generate (e.g., Home, Article)"
    default: "Home"
""")

create_dir(f"{feature_src_dir}/domain/repository")
with open(f"{feature_src_dir}/domain/repository/{{{{feature_name.pascalCase()}}}}Repository.kt", "w") as f:
    f.write("""package {{package_name}}.domain.repository

import {{package_name}}.domain.model.Resource
import kotlinx.coroutines.flow.Flow

interface {{feature_name.pascalCase()}}Repository {
    // suspend fun getData(): Flow<Resource<Any>>
}
""")

create_dir(f"{feature_src_dir}/data/repository")
with open(f"{feature_src_dir}/data/repository/{{{{feature_name.pascalCase()}}}}RepositoryImpl.kt", "w") as f:
    f.write("""package {{package_name}}.data.repository

import {{package_name}}.domain.repository.{{feature_name.pascalCase()}}Repository
import {{package_name}}.domain.model.Resource
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.flow
import javax.inject.Inject

class {{feature_name.pascalCase()}}RepositoryImpl @Inject constructor() : {{feature_name.pascalCase()}}Repository {
    // override suspend fun getData(): Flow<Resource<Any>> = flow { }
}
""")

create_dir(f"{feature_src_dir}/presenter/{{{{feature_name.snakeCase()}}}}")
with open(f"{feature_src_dir}/presenter/{{{{feature_name.snakeCase()}}}}/{{{{feature_name.pascalCase()}}}}ViewModel.kt", "w") as f:
    f.write("""package {{package_name}}.presenter.{{feature_name.snakeCase()}}

import androidx.lifecycle.ViewModel
import dagger.hilt.android.lifecycle.HiltViewModel
import {{package_name}}.domain.repository.{{feature_name.pascalCase()}}Repository
import javax.inject.Inject

@HiltViewModel
class {{feature_name.pascalCase()}}ViewModel @Inject constructor(
    private val repository: {{feature_name.pascalCase()}}Repository
) : ViewModel() {
    // TODO: Implement ViewModel logic
}
""")

with open(f"{feature_src_dir}/presenter/{{{{feature_name.snakeCase()}}}}/{{{{feature_name.pascalCase()}}}}Fragment.kt", "w") as f:
    f.write("""package {{package_name}}.presenter.{{feature_name.snakeCase()}}

import android.os.Bundle
import android.view.View
import androidx.fragment.app.Fragment
import androidx.fragment.app.viewModels
import dagger.hilt.android.AndroidEntryPoint

@AndroidEntryPoint
class {{feature_name.pascalCase()}}Fragment : Fragment() {

    private val viewModel: {{feature_name.pascalCase()}}ViewModel by viewModels()

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        // setupObservers()
    }
}
""")

print(f"✅ Success! STANDALONE mason bricks created in {base_templates_dir}!")
